.TH BFAUXPWR 8 "June 2020"
.SH NAME
bfacpievt \- Create configuration files to handle acpi events.
.SH SYNOPSIS
.B bfacpievt
.RB [ \-\-help | \-h ]
.PP
.B bfacpievt --update-acpi-low-pwr
.SH DESCRIPTION
Create configuration files to handle acpi events. Currently, this script is
only applicable to OCP 3.0 to handle low power mode.
.SH OPTIONS
.IP --update-low-pwr
Disable power button event handling in systemd, and configure the ACPI daemon
to handle AUX power events by powering up/down all secondary cores. This option
is only valid for the OCP 3.0 card.
