.TH BFAUXPWR 8 "June 2020"
.SH NAME
bfauxpwr \- Configure an OCP 3.0 card to handle AUX power mode
.SH SYNOPSIS
.B bfauxpwr
.RB [ \-\-help | \-h ]
.PP
.B bfauxpwr --update-acpi
.SH DESCRIPTION
Enables AUX power mode handling on OCP 3.0 BlueField 2 cards. Called with no
arguments, this script will do nothing.
.SH OPTIONS
.IP --update-acpi
Disable power button event handling in systemd, and configure the ACPI daemon
to handle AUX power events by powering up/down all secondary cores.
