.TH BFFINDFW 8 "July 2020"
.SH NAME
bffindfw \- Print the path to network adapter FW for current platform
.SH SYNOPSIS
.B bffindfw
.SH DESCRIPTION
Searches the filesystem for the ConnectX firmware distribution appropriate
for the current BlueField hardware revision and linux distribution, and prints
the absolute file path to stdout.
.SH OPTIONS
.B bffindfw
takes no options.
