.TH BFPXE 8 "June 2020"
.SH NAME
bfpxe \- Set up network configuration and run remote script during PXE boot
.SH SYNOPSIS
.B bfpxe
.SH DESCRIPTION
This script reads Linux kernel arguments to get the networking configuration
and a remote file which is usually an automated script. It sets up the network
as specified then downloads and executes the file.
.SH OPTIONS
.B bfpxe
takes no options.
.SH KERNEL ARGUMENTS
.IP bfks=<PATH>
HTTP path for the shell script. For example,
.I http://192.168.100.1/ks/bf-install.sh
.IP "bfnet=<IFNAME>:<IPADDR>:<NETMASK> or <IFNAME>:dhcp"
Network configuration entry. IFNAME can have ".", which indicates VLAN
interface, such as "tmfifo_net0.100:dhcp".
