.TH BFREC 8 "June 2020"
.SH NAME
bfrec \- Install boot firmware to the bluefield eMMC
.SH SYNOPSIS
.B bfrec
.RB [ \-\-help ]
.RB [ \-\-bootctl
.RI [ FILE ]]
.RB [ \-\-capsule
.RI [ FILE ]]
.RB [ \-\-policy
.IR POLICY ]
.SH DESCRIPTION
Installs boot firmware FILE to the bluefield eMMC with one of two methods,
as described in
.B OPTIONS.
The system must be rebooted for the installation to take effect.
.PP
If no FILE, use
.I /lib/firmware/mellanox/boot/default.bfb
.SH OPTIONS
.IP "--bootctl [FILE]"
Install firmware using the
.B mlxbf-bootctl
utility. 
.IP "--capsule [FILE]"
Set up a UEFI capsule install using FILE. The installation will take place
after reboot.
.IP "--policy POLICY"
Sets the update policy. May be either "single" or "dual". "single" will
update only the secondary boot partition and swap to it. "dual" will update
both at once. The default is "single".
