.TH BFRTC-POLL 8 "July 2026"
.SH NAME
bfrtc-poll \- Read RTC time to trigger firmware repair of invalid dates
.SH SYNOPSIS
.B bfrtc-poll
.SH DESCRIPTION
Reads the hardware RTC and discards the output. The RTC read triggers firmware
repair of invalid RTC dates on affected BlueField systems.
.SH OPTIONS
.B bfrtc-poll
accepts no options.
