.TH BFVCHECK 1
.SH NAME
bfvcheck \- verifies that installed firmware versions match recommended
.SH SYNPOSIS
.B bfvcheck
.SH DESCRIPTION
Verifies that installed UEFI, ATF and ConnectX firmware match versions tested
with the current operating system. This script compares by equality, and will
exit in failure even if the installed version exceeds the recommended one.
.SH OPTIONS
.B bfvcheck
takes no options.
