.TH BFVER 8 "June 2020"
.SH NAME
bfver \- print bluefield software version information
.SH SYNOPSIS
.B bfver
.SH DESCRIPTION
Print the version of the ATF and UEFI firmware currently installed to
the chip's eMMC, as well as the installed version of the Yocto filesystem, if
present. The user running this script must have read access to
.IR /dev/mmcblk0* .
.SH OPTIONS
.B bfver
accepts no options.
