#!/bin/bash
#
# SPDX-FileCopyrightText: Copyright (c) 2017-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
#

chip=$(bffamily --chip 2>/dev/null)
if [ $? -ne 0 ] || [ -z "$chip" ]; then
  echo "Error: Unable to determine BlueField chip family" >&2
  exit 1
fi

case "$chip" in
  BlueField-3|BlueField-4)
    echo "No live frequency reporting is supported at this time" >&2
    echo "core freq = -1 MHz"
    exit 0
    ;;
  Unknown)
    echo "Error: Unknown BlueField chip family" >&2
    exit 1
    ;;
esac

if [ ! -r /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq ]; then
  # Cannot access cpufreq driver on BF-1 and BF-2. Use SMBios table instead.
  msg=$(dmidecode -s processor-frequency)    # showing "XXX MHz"
else
  khz=$(cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq)
  if ! [[ "$khz" =~ ^[0-9]+$ ]]; then
    echo "Error: Invalid frequency value read: $khz KHz" >&2
    exit 1
  fi
  msg="$((khz/1000)).$((khz%1000)) MHz"
fi
echo "core freq = $msg"
