.TH BFPERF_BF3_PMC 8 "March 2024"
.SH NAME
bfperf_pmc \- BlueField SoC Telemetry Monitoring
.SH SYNOPSIS
.B bfperf_pmc
.RB [ \-\-help | \-h ]
.RB [ \-\-sleep | \-s
.IR SLEEP ]
.RB [ \-\-verbose | \-v ]
.SH DESCRIPTION
This tool uses the BlueField-3 Performance counters to compute various
memory-related performance metrics.
.SH OPTIONS
.IP "--sleep | -s SLEEP"
Sample period in seconds.
